### ISSUE TITLE
Use custom vue component as CRUD field and save data

### ISSUE THREAD

**Issue by albertpratomo** [aw-studio/laravel-content-administration#48]
![image](https://user-images.githubusercontent.com/25815584/87859963-aa8e6900-c939-11ea-97ab-8cc32175482f.png)

Hi, I managed to make a custom Vue component that display a Google Map in the show page of my CRUD model. I want to use the data inside this Vue component to update my model.

Questions:
1. Is it possible to include this data when "Save" button on top right is clicked? Or do I have to make my own axios request?
2. If 1 is possible, how do I update the controller that will process the sent data and update the database?

Suggestion:
1. When creating this custom component, I had to use `<fj-base-field>` component to achieve the same form-group look as the other fields. I think it would be nice if in my `CrudConfig.php`, I can do something like `$form->component('input-google-map')->title('Address');`, and then my custom component would be wrapped inside `<fj-base-field>` and the label is shown.

Much thanks!

**Comment by cbl** [comment]
Hi. It is possible to add requests that should be send when hitting the save button. I think the easiest solution for this case is to create a custom map field. It is not yet documented how this works. We plan to write more in-depth documentation, but we want to think carefully about how to do that to avoid breaking changes.

# Creating a custom Field

First of all you need to create the field class that extends `Fjord\Crud\BaseField`:

```php
use Fjord\Crud\BaseField;

class MapField extends BaseField
{
    /**
     * Field Vue component.
     *
     * @var string
     */
    protected $component = 'my-map-field-component';

    public function foo($value)
    {
        $this->setAttribute('foo', $value);
    
        return $this;
    }
}
```

Next we are going to register the field in a ServiceProvider, so it can be used on your crud page:

```php
use Fjord\Support\Facades\Form;

Form::registerField('map', MapField::class)->foo('bar');
````

We are now able to use the field like so:

```php
$form->map('location')->title('Address');
```

Our final step is to create the Vue component for the Field. The component receives the props `field` and `value`. The `field` is an object containing all attributes of the field. The value contains the model value. In this case it would be the value of the database column `location`.
If we want to update the value we just need to emit `input` with the updated value, like shown in the example:

```javascript
<template>
    <fj-base-field :field="field">
        <!-- ... -->
    </fj-base-field>
</template>

<script>
export default {
    name: 'FieldCheckboxes',
    props: {
        field: {
            required: true,
            type: Object
        },
        value: {
            required: true
        }
    },
    methods: {
        update(value) {
            this.$emit('input', value)
        }
    }
};
</script>
```

The update method can be called with the new value. This will update the prop `value` the value will be saved to `location` when the save button is hit.

**Comment by albertpratomo** [comment]
@cbl Hi, thanks for the answer. I followed the steps above and ran into an error:

```
Illuminate \ Contracts \ Container \ BindingResolutionException
Target class [fjord.form] does not exist.
Previous exceptions
Class fjord.form does not exist (-1)
```

I suspect this has something to do with the `ServiceProvider` and the `FormFacade` to register the field.

In which `ServiceProvider` should I do this? Also is there anything else I should do prior to registering the field?

**Comment by albertpratomo** [comment]
Got it working by doing this before registering the field:

```
$this->app->singleton('fjord.form', function () {
            return new Form();
        });
```

**Comment by cbl** [comment]
@albertpratomo Hey, if your ServiceProvider requires a binding that has not been resolved yet you could wait for it using the `afterResolving` lifecycle hook.

```php
$this->app->afterResolving('fjord.form', function($form) {
    $form->registerField('map', ...);
});
```

**Comment by albertpratomo** [comment]
> @albertpratomo Hey, if your ServiceProvider requires a binding that has not been resolved yet you could wait for it using the `afterResolving` lifecycle hook.
> 
> ```
> $this->app->afterResolving('fjord.form', function($form) {
>     $form->registerField('map', ...);
> });
> ```

This solution works, thanks!

**Comment by albertpratomo** [comment]
I have another question. Currently this is my DB structure:
- `Store` model with `belongsTo` relation to `Address` (`stores` table has `address_id`)
- `Address` model with `hasOne` relation to `Store`

With Fjord, can I create/edit `Address` data (street, number, city) using the `Store` CRUD form? Or do you recommend having `Address` CRUD form and linking Store to Address?

Much thanks!

**Comment by cbl** [comment]
Hey, I recommend having a CRUD config for every model you want to make editable. You may have multiple CRUD configs for one model but you cannot mix up different models in one config file.

**Comment by albertpratomo** [comment]
Okay, but at least I can have a link to the related `Address` model in the `Store` edit form, right?

What would be the best way to achieve this? (I don't really understand the `oneRelation` and `manyRelation` in the [docs](https://relaxed-lovelace-429a31.netlify.app/docs/fields/one_relation.html)).

**Comment by cbl** [comment]
The `relation` field makes your laravel relations editable so it can be used for `belongsTo`, `hasOne`, `hasMany`, .... However the `oneRelation` and `manyRelation` does not need a database setup that the laravel relations need, for example when you want to create a belongsTo relation you need a column like `adress_id`  that stores the related id. `oneRelation` does not need an extra column for that.

I would recommend to create a relation field in your `store` config like this:

```php
$form->relation('address')->title('Adress')->preview(...);
```

Assuming that your store model has the following relation method:

```php
public function address()
{
    return $this->belongsTo('App\Models\Address');
}
```

**Comment by albertpratomo** [comment]
@cbl Clear, thank you!!

**Comment by albertpratomo** [comment]
Hi @cbl, I have a follow-up to the question above.

![image](https://user-images.githubusercontent.com/25815584/89123169-90be5b80-d4cd-11ea-989c-9dc6ce72afad.png)

I have the custom `Map` component. I wish that by clicking "Select" button, some data could be copied to the fields above. The fields above (street, number, etc) are created using Fjord input fields.

Current config:
```
public function show(CrudShow $page): void
    {
        $page->card(function($form) {
            // Link to store.
            $form->relation('store')
                ->readonly(true)
                ->title('Store')
                ->type('link')
                ->linkValue('{name}');
            
            $form->input('street')->title('Street')->width(6);

            $form->input('number')->title('Number')->width(3);

            $form->input('city')->title('City')->width(3);

            $form->input('lat')->title('Latitude')->width(6);

            $form->input('lng')->title('Longitude')->width(6);

            $form->input('gmaps_place_id')->title('Google Maps Place ID');

            // Custom component to help select address via Google Maps.
            $form->component('input-address-gmap');
        });
    }
```

Do you have a suggestion on how to achieve this?

**Comment by cbl** [comment]
In that case I would recomment to use fill the input values using Javascript in your `input-address-gmap`component. There might be smarter ways to solve this.
