### ISSUE TITLE
No navigation entry preset with name "user.user" found.

### ISSUE THREAD

**Issue by noukentosh** [aw-studio/laravel-content-administration#51]
When installing on a clean copy of Laravel, it is not possible to log into _/admin_, if you forcibly go to _/admin/login_ and log in as an administrator, then a similar error appears.

**Comment by cbl** [comment]
Seem like fjord is not able to read your folder structure. It attemps to read the config file located in `./fjord/app/Config/User/UserConfig.php`.

What operating system are you working on?

This is a duplicate from https://github.com/aw-studio/laravel-content-administration/issues/26

**Comment by noukentosh** [comment]
> What operating system are you working on?

Windows 10 Last production build, Apache 2.4 + Nginx 1.17 + PHP 7.4

Reading and executing allowed for the file.

**Comment by cbl** [comment]
I'm guessing that some windows file path stuff is going on here. Does the file `./fjord/app/Config/User/UserConfig.php ` exist? Another thing could be that the preset is not found due to route caching. You could try `php artisan route:clear` to clear the route cache.

Unfortunatelly I cannot reproduce the bug on a windows operating system at the moment.

**Comment by noukentosh** [comment]
![image](https://user-images.githubusercontent.com/11080918/88578519-5d08af00-d051-11ea-8f9f-f4c72c0c90a4.png)

I cleaned the cache, it did not help.

**Comment by noukentosh** [comment]
https://gist.github.com/noukentosh/3ad076b3b6f63ab3f19b2c7d11d1b493

Crutch, but it works.

**Comment by cbl** [comment]
This schould fix the issue: https://github.com/aw-studio/laravel-content-administration/commit/4a26188068b3da52a8e5c6d6fba7bb44e08ac77d

**Comment by toilaai** [comment]
> This schould fix the issue: [4a26188](https://github.com/aw-studio/laravel-content-administration/commit/4a26188068b3da52a8e5c6d6fba7bb44e08ac77d)

Thanks, it work for me. I think you should create new PR :)
