### ISSUE TITLE
Assets loaded over HTTP should be loaded over HTTPS

### ISSUE THREAD

**Issue by albertpratomo** [aw-studio/laravel-content-administration#53]
Hi, I tried to deploy my Fjord app to a staging environment and got this error:
![image](https://user-images.githubusercontent.com/25815584/89465245-119d8180-d772-11ea-9581-13b7849976ff.png)

One of the effect is the Vue components are not translating properly. I believe it has something to do with `vendor\aw-studio\fjord\resources\views\index.blade.php:56`

The code:
```
<!-- fjord translations -->
<script src="{{ fjord()->route('fjord-translations') }}"></script>
```

Looks like `fjord()->route()` is returning an absolute path with HTTP. How can I get a HTTPS path instead?

Thanks.

**Comment by cbl** [comment]
Could it ne that your `APP_URL` Environment variable ist mit set to the `https://...` url? 🤔

**Comment by albertpratomo** [comment]
Hmm I didn't specify that env variable actually. I tried changing it just now but it doesn't affect anything 😐

**Comment by cbl** [comment]
This problem occures due to the default `http`scheme from the Laravel url generator. You can solve the problem by placing the following snippet in your service provider:

```php
use Illuminate\Support\Facades\URL;

URL::forceScheme('https');
```

This thread addresses the problem: https://stackoverflow.com/questions/44409807/laravel-https-routes
