### ISSUE TITLE
Error on relation column

### ISSUE THREAD

**Issue by Dezodev** [aw-studio/laravel-content-administration#63]
Hello,

I just started a site with your project.

I created a model (Frequency) with two relations: a Many to Many to link cities and a One to Many to link a radio.

I would like to display the name of the linked radio in the table, but I have the following error.

> Return value of Fjord\Crud\CrudColumnBuilder::component() must implement interface Fjord\Contracts\Page\Column, null returned

I put the code concerned below.

_app/Models/Frequency.php_
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Fjord\Crud\Models\Traits\TrackEdits;

class Frequency extends Model
{
	use TrackEdits;

	/**
	 * Fillable attributes
	 *
	 * @var array
	 */
	protected $fillable = [
		'frequency', 'active', 'radio_id'
	];

	protected $casts = [
		'active' => 'boolean'
	];

	public function cities() {
		return $this->belongsToMany('App\Models\City');
	}

	public function radio() {
		return $this->belongsTo('App\Models\Radio');
	}
}

```

_app/Models/Radio.php_
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Fjord\Crud\Models\Traits\TrackEdits;
use Spatie\MediaLibrary\HasMedia as HasMediaContract;
use Fjord\Crud\Models\Traits\HasMedia;
use Fjord\Crud\Models\Traits\Sluggable;

class Radio extends Model implements HasMediaContract
{
	use TrackEdits, HasMedia, Sluggable;

	[...]

	public function frequencies() {
		return $this->hasMany('App\Models\Frequency');
	}
}

```

_fjord/app/Config/Crud/FrequencyConfig.php_
```php
<?php

namespace FjordApp\Config\Crud;

use Fjord\Crud\CrudShow;
use Fjord\Crud\CrudIndex;
use Fjord\Crud\Config\CrudConfig;
use Illuminate\Support\Str;

use App\Models\Frequency;
use App\Models\Radio;
use FjordApp\Controllers\Crud\FrequencyController;

class FrequencyConfig extends CrudConfig
{
	[...]

	/**
	 * Build index page.
	 *
	 * @param Fjord\Crud\CrudIndex $page
	 * @return void
	 */
	public function index(CrudIndex $page)
	{
		// Expand html container to full width.
		$page->expand(false);

		$page->table(function ($table) {
			$table->col('Fréquence')->value('{frequency}')->sortBy('frequency');

			$table->relation('Radio')
				->related('radio') // Relation name.
				->value('{name}') // Related attribute to be displayed.
				->routePrefix(
					Crud::config(Radio::class)->route_prefix
				);
		})
			->sortByDefault('id.desc')
			->search('frequency')
			->sortBy([
				'id.desc' => __f('fj.sort_new_to_old'),
				'id.asc' => __f('fj.sort_old_to_new'),
			])
			->width(12);
	}

	[...]
}

```

I also give you the stack trace of the error.

![](https://i.ibb.co/bRXz25S/Capture-d-e-cran-2020-08-18-a-14-05-56.jpg)

Can you help me solve the problem?

thank you,
Deniz.

**Comment by cbl** [comment]
Hello Deniz,

Can I see the corresponding Config?

**Comment by Dezodev** [comment]
Sorry, my message went too fast. :)

I modified the first post.

Deniz.

**Comment by cbl** [comment]
This should fix the bug: https://github.com/aw-studio/laravel-content-administration/commit/d3577723da195cabfd1a341b226aa180f2375752

Additionally I noticed `Crud::config` is deprecated. Use this instead:

```php
use Fjord\Support\Facades\Config;

Config::get(Radio::class)->route_prefix
```

**Comment by Dezodev** [comment]
The fix worked well for my first bug.

Now I have another error: "Trying to get property 'route_prefix' of non-object".

The `Config::get` function returns null.

Deniz.

**Comment by cbl** [comment]
Use `Config::get(RadioConfig::class)` instead.

**Comment by Dezodev** [comment]
Hi,

Sorry to bother you again. I am coming back to you because I have another problem. The code you gave me worked.

On the radio link, his name is missing and the link leads to a 404 page. Without the `/edit`, the link works.

![](https://i.ibb.co/7QDd95D/2020-08-18-22-16-38.jpg)

Thank you,
Deniz.

**Comment by cbl** [comment]
Hey Deniz, thank you for the feedback. The `edit` suffixed link was related to an outdated version where the detail page was available through that link.

This should fix the bug https://github.com/aw-studio/laravel-content-administration/commit/84d1a82d70037cb2a0310fe61a394f4e922ab2be

**Comment by Dezodev** [comment]
Hello,

I just used your code to fix the links and it worked.

For the display of the name of the relation, I was able to correct it by modifying the code.

In the getColValue function of the TableCol.vue file, the "col" parameter had for value the following character string: "{name}".

I add an if loop on the type of the parameter and put the parameter in the value variable if it's a string.

The code is below.

_resources/js/components/Fjord/BaseIndex/TableCol/TableCol.vue_
```js
getColValue(col, item) {
	let value = '';
	let col_type = typeof col;

	if (col_type == "object") {
		if (col.value_options) {
			value = col.value_options[item[col.value]];

			if (value === undefined && col.default_value) {
				value = col.default_value;
			}
		} else {
			value = col.value;
		}
	} else if (col_type == "string") {
		value = col;
	}

	// Regex for has {value} pattern.
	if (/{(.*?)}/.test(value)) {
		value = this._format(value, item);
	} else if (item[value] !== undefined && item[value] !== null) {
		value = item[value];
	}

	return this.format(value);
},
```

I don't know if that can help you.

Regards,
Deniz.

**Comment by cbl** [comment]
Thanks, that has been fixed as well.
