### ISSUE TITLE
Call to undefined method Ignite\Foundation\Litstack::trans_choice()

### ISSUE THREAD

**Issue by YashPatel2020** [aw-studio/laravel-content-administration#68]
when I am trying to delete that time I have got an error 
 
BadMethodCallException
![Screenshot_1](https://user-images.githubusercontent.com/60727030/94395389-36641300-017d-11eb-8890-5a1b90a91fcf.png)
Call to undefined method Ignite\Foundation\Litstack::trans_choice()

**Comment by cbl** [comment]
Thanks.

This is now fixed and tested: https://github.com/aw-studio/laravel-content-administration/commit/0d7c35517b84be7cc3cff477a5acef49516cf031
